settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 15 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: na-edu
    name: NA.Edu
    description: 'North American University'
    url: 'https://www.na.edu'
    
  - id: portal-na-edu
    name: Portal.NA.Edu
    description: 'MyNAU Student Portal'
    url: 'https://portal.na.edu/ics'
    
  - id: shop-na-edu
    name: Shop.NA.Edu
    description: 'NAU Shop (ecommerce)'
    url: 'https://shop.na.edu'
    
  - id: office-com
    name: Office.com
    description: 'Microsoft Office'
    url: 'https://www.office.com'
    
  - id: outlook-office-com
    name: Outlook.Office.com
    description: 'Microsoft Office Outlook Email'
    url: 'https://outlook.office.com'
    expectStatus: 301 # Should redirect to /owa for authentication
    
  - id: netacad-com
    name: NetAcad.com
    description: 'Cisco Networking Academy'
    url: 'https://www.netacad.com'
    
  - id: bing-com
    name: Bing.com
    description: 'Bing Search Engine'
    url: 'https://www.bing.com'
    
    # Available vars
#   - id: workers-cloudflare-com # unique identifier
#     name: workers.cloudflare.com
#     description: 'You write code. They handle the rest.' # default=empty
#     url: 'https://workers.cloudflare.com/' # URL to fetch
#     method: GET # default=GET
#     expectStatus: 200 # operational status, default=200
#     followRedirect: false # should fetch follow redirects, default=false
#     linkable: false # allows the title to be a link, default=true
